#=============================================================================
#=============================================================================

obj-$(CONFIG_HW_ANTENNA_BOARD_MATCH)  += antenna_board_match/
obj-$(CONFIG_HUAWEI_AUDIO) += audio/
obj-$(CONFIG_CHR_NETLINK_MODULE)   += chr/
obj-y   += connectivity/
obj-$(CONFIG_HUAWEI_HW_DEV_DCT)  += devdetect/
obj-y   += inputhub/
obj-$(CONFIG_NFC_DEVICES)   += nfc/
obj-$(CONFIG_HW_WIFI)   += net/
obj-y   += power/
obj-$(CONFIG_HUAWEI_DSM) += recovery/
obj-$(CONFIG_HUAWEI_SENSORS_INPUT_INFO)   += sensor/
obj-y   += storage/
obj-$(CONFIG_HUAWEI_TS)   += touthscreen/
obj-y   += usb/
obj-$(CONFIG_ANTENNA_BOARDID_GPIO_DETECT) += antenna_board_gpio_match/
obj-$(CONFIG_HUAWEI_OCP) += ocp/
obj-$(CONFIG_MADAPT) += madapt/
obj-$(CONFIG_HW_LED_ALWAYSON) += led_alwayson/
obj-$(CONFIG_HUAWEI_BOOT_TIME) += boottime/
obj-y   += hw_led/
obj-$(CONFIG_HUAWEI_EMCOM) += emcom/
obj-$(CONFIG_HUAWEI_VENDOR_EXCEPTION) += vendor_exception/
