#
# FLP PDR configuration
#
ccflags-y  += -I$(srctree)/drivers/huawei_platform/inputhub/hi6250/
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
obj-$(CONFIG_HISI_FLP)	+=hisi_softtimer.o hisi_flp.o hisi_flp_dt.o hismart_ar.o
